### ISSUE TITLE
Where is the Android App (apk)?

### ISSUE THREAD

**Issue by Gerriko** [cypresssemiconductorco/Code-Examples-BT-SDK-for-ModusToolbox#2]
Sorry your documentation is very scant. I was redirected to this page from IOTexpert.com Mesh page which apparently uses an old github reference that gives a redirect to here. 

Now I cannot find anything.

I am particularly looking for the Android App files. No direction given in the ReadMe files.

This is very frustrating. If you are going to race ahead please please keep a documentation trace to help us follow and keep track of all your changes.

**Comment by madhusudhan-made** [comment]
Hi Gerriko,

Are you looking for MeshLightingController.apk?

**Comment by Gerriko** [comment]
Yes.

**Comment by madhusudhan-made** [comment]
I have attached the .apk to this message.

Also you can find the .apk if you follow this folder structure: ModusToolbox_1.1/libraries/bt_20819A1-1.0/components/BT-SDK/common/apps/snip/mesh/peerapps/Android/src/bin

Android Source code is available in this folder structure: ModusToolbox_1.1/libraries/bt_20819A1-1.0/components/BT-SDK/common/apps/snip/mesh/peerapps/Android/src/MeshApp

[MeshLightingController.zip](https://github.com/cypresssemiconductorco/Code-Examples-BT-SDK-for-ModusToolbox/files/3432005/MeshLightingController.zip)

**Comment by Gerriko** [comment]
Thank you. Not sure if you can provide a quick answer (and realise a different topic), but is there any reason why I cannot use Android version 5.x (documentation says app is for Android 7)

**Comment by madhusudhan-made** [comment]
I am not sure, worked fine since I have Android 9, let me check into the source code and get back on this.

**Comment by Gerriko** [comment]
Thanks. My phones and tablets are not that new. All Android 5.1x

**Comment by madhusudhan-made** [comment]
I went through the android code, I see that the minimum target SDK is 23 which means the app can run only on Android 6.0 and above.

My theory is this, it has been set because of Android's "Filtering scan results" which requires 6.0 and above, there is nothing much we can do around this since it is an android requirement, check out this link for more information: [Android Filtering scan results ](https://source.android.com/devices/bluetooth/ble#filtering-scan-results).

@JimTrudeau @abhaydandekar @cygitlab-user can you please confirm, this is the case and then close this issue.

**Comment by Gerriko** [comment]
Thank you very much for your detailed and thoughtful feedback. I really appreciated the link to Android Filtering as it saved me from having to search for it myself.  Happy to wait for final confirmation, then you can close this issue. Thanks again for your replies.
